spring:
  application:
    name: bankrest
  datasource:
    url: jdbc:postgresql://localhost:5432/bankrest
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:db/migration/db.changelog-master.yml

app:
  pagination:
    limit: 5

server:
  port: 8080

jwt:
  access:
    secret: pCUDF0J7Z/bKD8wysWJIzyv5AabF4Ug2P7t3Hk7aSkIi4Z1sUpFFIPTha4tbr/Kt5E6rLabIwCR1xQVmALsiRA==
    exp_time: 3000000

Что нужно сделать:
  - Указать настройки подключения к базе данных.
  - Указать порт приложения.
  - Настроить параметры безопасности и JWT.
  - Включить Swagger UI.